kind: pipeline
name: default

steps:
- name: compile
  image: node:7
  environment:
    token:
      from_secret: token
  commands:
  - npm install gitbook-cli -g
  - ./ci.sh compile
  - ./ci.sh deploy
